### ISSUE TITLE
Class diagrams in README.md & pypi broken

### ISSUE THREAD

**Issue by alinsavix** [sfanous/Pyecobee#25]
As the subject says, the class diagrams intended to be shown as part of README.md (and thus on pypi) are broken, with the github CDN simply responding `Error Fetching Resource`. These would be useful, so it would begreat if they were able to be returned to their former glory. <3

**Comment by sherif-fanous** [comment]
Thanks for noticing that. I didn't even know <https://rawgit.com> had reached end of life. I'll fix it shortly.

**Comment by sherif-fanous** [comment]
Fixed

**Comment by alinsavix** [comment]
<3
