### ISSUE TITLE
Question: Can this lib detect when Eco+ mode is turned on?

### ISSUE THREAD

**Issue by jeeftor** [sfanous/Pyecobee#28]
I'm wondering if you can detect when eco+ mode is turned on. I'm unclear from the API where that would be.

**Comment by sherif-fanous** [comment]
Hey @jeeftor

I'm not sure and a quick ecobee documentation didn't lead me to any answers.

To be frank this question would be better asked to ecobee support themselves.

I'll close this issue but feel free to open it if you figure out how and Pyecobee isn't supporting it.
