### ISSUE TITLE
pyecobee for MicroPython on the Raspberry Pi PICO W

### ISSUE THREAD

**Issue by nanowiz** [sfanous/Pyecobee#32]
I would really like to see a subset of pyecobee that would work with MicroPython on the Raspberry Pi PICO W. I am trying to control various devices in the house and requires only the basic info from my Ecobee Thermostat like the running state of the furnace and the temperatures from the various sensors. Current, the size of the pyecobee library is so large that it will not even fit into the available file space on the PICO W without compilation first.

**Comment by sherif-fanous** [comment]
Unfortunately maknig the library compatible with MicroPython falls outside the current scope and intended direction of the project. Making a Python library compatible with MicroPython involves a substantial amount of work, including but not limited to, reviewing and potentially refactoring dependencies, optimizing for memory and performance constraints, and extensive testing in a MicroPython environment.

PRs are welcome though
