### ISSUE TITLE
tokens keep expiring, generates fine.

### ISSUE THREAD

**Issue by 88gts** [sfanous/Pyecobee#7]
I can generate a token and it works for an hour, but shortly after expires.  I call the refresh, still no dice.  Simply trying to toggle the status of my thermostat with this script.  I have noticed that pyecobee_db is not taking any changes, even after calling the refresh.  The only way to fix is wipe away the db and provide the 4 digit code to ecobee...trying to integrate this into my own automation.  Thanks!

    thermostat_name = 'Home'
    try:
        pyecobee_db = shelve.open('/var/www/scripts/notify/ecobee/pyecobee_db', protocol=2)
        ecobee_service = pyecobee_db[thermostat_name]
    except KeyError:
        application_key = input('Please enter the API key of your ecobee App: ')
        ecobee_service = EcobeeService(thermostat_name=thermostat_name, application_key=application_key)
    finally:
        pyecobee_db.close()

    if not ecobee_service.authorization_token:
        authorize(ecobee_service)

    if not ecobee_service.access_token:
        request_tokens(ecobee_service)

    now_utc = datetime.now(pytz.utc)
    if now_utc > ecobee_service.refresh_token_expires_on:
        authorize(ecobee_service)
        request_tokens(ecobee_service)
    elif now_utc > ecobee_service.access_token_expires_on:
        token_response = ecobee_service.refresh_tokens()

    try:
        thermostat_summary_response = ecobee_service.request_thermostats_summary(selection=Selection(
        selection_type=SelectionType.REGISTERED.value,
        selection_match='',
        include_equipment_status=True))
    except EcobeeApiException as e:
        if e.status_code == 14:
            token_response = ecobee_service.refresh_tokens()

    selection = Selection(selection_type=SelectionType.REGISTERED.value, selection_match='',include_equipment_status=True)
    
    thermostat_response = ecobee_service.request_thermostats(selection)    
    print thermostat_response

returns the following once expired
```
Traceback (most recent call last):
  File "status2.py", line 69, in <module>
    token_response = ecobee_service.refresh_tokens()
  File "/usr/local/lib/python2.7/dist-packages/pyecobee/service.py", line 218, in refresh_tokens
    tokens_response = Utilities.process_http_response(response, EcobeeTokensResponse)
  File "/usr/local/lib/python2.7/dist-packages/pyecobee/utilities.py", line 349, in process_http_response
    error_response.error_uri)
pyecobee.exceptions.EcobeeAuthorizationException: ecobee authorization error encountered for URL => https://api.ecobee.com/token?code=&client_id=&grant_type=refresh_token
HTTP error code => 400
Error type => invalid_grant
Error description => The authorization grant, token or credentials are invalid, expired, revoked, do not match the redirection URI used in the authorization request, or was issued to another client.
Error URI => https://tools.ietf.org/html/rfc6749#section-5.2
```

**Comment by hudcap** [comment]
The error you posted appears to include your refresh token (valid for a year) and api key (valid indefinitely), neither of which you should probably be posting publicly.
I would recommend you invalidate both of them, since they can now be considered compromised.

**Comment by hudcap** [comment]
@88gts I see you edited it to remove the tokens, but the previous version is still accessible.
I would highly recommend that you still invalidate both of them.

**Comment by lukedemi** [comment]
I am experiencing the same issues over here

**Comment by 88gts** [comment]
> I am experiencing the same issues over here

I was not executing from my home directory so my bash script was failing to update the db.  basically have a bash script polling every few minutes and call the refresh token each time.  added the following to do that...

    pyecobee_db = shelve.open('/var/www/scripts/notify/ecobee/pyecobee_db', protocol=2)
    ecobee_service = pyecobee_db['Home']
    token_response = ecobee_service.refresh_tokens()
    pyecobee_db[ecobee_service.thermostat_name] = ecobee_service
    pyecobee_db.close()
