### ISSUE TITLE
Readme Typo in Persistence Section

### ISSUE THREAD

**Issue by adorsett** [sfanous/Pyecobee#8]
In your persistence example you execute
`token_response = ecobee_service.refresh_tokens()`

This calls the wrong refresh_tokens() resulting in the refreshed token not being written to shelve and thus an eventual 400 error once your access token expires.

It should be:
``token_response = refresh_tokens(ecobee_service)``

**Comment by sherif-fanous** [comment]
Nice catch. Just pushed a fix.
